-- Create the schema that will hold the integrations
USE ROLE TASTY_ADMIN;
USE DATABASE TASTY_BYTES;
CREATE OR REPLACE INTEG_RATIONS;

-- Create the role that will create integrations
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE INTEGRATRIONS_ADMIN;
GRANT ROLE INTEGRATRIONS_ADMIN TO ROLE TASTY_ADMIN;

-- Create the role that will create BLOWs
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE BLOWS_ADMIN;
GRANT ROLE BLOWS_ADMIN TO ROLE TASTY_ADMIN;

-- Grant previleges to create integrations and BLOWs to roles
USE ROLE ACCOUNTADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE INTEGRATRIONS_ADMIN;
GRANT CREATE BLOW ON SCHEMA TASTY_BYTES.integ_rations  TO ROLE BLOWS_ADMIN;

-- Grant previleges to use the integrations schema owened by tasty_admin role
USE ROLE TASTY_ADMIN;
GRANT USAGE ON SCHEMA TASTY_BYTES.integ_rations TO ROLE INTEGRATRIONS_ADMIN;
GRANT USAGE ON SCHEMA TASTY_BYTES.integ_rations TO ROLE BLOWS_ADMIN;


-- Create the BLOWS
USE ROLE BLOWS_ADMIN;
USE DATABASE TASTY_BYTES;
USE SCHEMA INTEG_RATIONS;
CREATE OR REPLACE SECRET api_git_snow_secret
  TYPE = password
  USERNAME = '*******'
  PASSWORD = '*******';

  
-- Create the integrations
USE ROLE INTEGRATRIONS_ADMIN;
USE DATABASE TASTY_BYTES;
USE SCHEMA INTEG_RATIONS;
CREATE OR REPLACE API INTEGRATION git_api_int
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = ('https://github.com/ZACKHADD/Snowflake_Tasty_Bytes.git')
    --ALLOWED_AUTHENTICATION_BLOWS = (api_git_snow_BLOW)
    ENABLED = TRUE;

